name: ci

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spa-java-spring-boot-template/src/main/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - name: Setup Yarn
        working-directory: ./src/main/frontend/
        run: npm install -g yarn
      - name: Yarn install
        run: yarn install
      - name: Yarn build
        run: yarn run build
  build-and-push-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spa-java-spring-boot-template/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
          architecture: x64
      - name: Maven package
        run: mvn -B package --file pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t vartdalen/spa-java-spring-boot-template:latest .
        if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/master') }}
      - name: Docker build and push
        run: docker buildx build --platform linux/amd64,linux/arm64 -t vartdalen/spa-java-spring-boot-template:latest . --push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
